# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gpd_ros/detect_graspsRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import gpd_ros.msg
import sensor_msgs.msg
import std_msgs.msg

class detect_graspsRequest(genpy.Message):
  _md5sum = "f5aafbcfa3b48e6d646c19e1a4b3b6f7"
  _type = "gpd_ros/detect_graspsRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """gpd_ros/CloudIndexed cloud_indexed

================================================================================
MSG: gpd_ros/CloudIndexed
# This message holds a point cloud and a list of indices into the point cloud 
# at which to sample grasp candidates.

# The point cloud.
gpd_ros/CloudSources cloud_sources

# The indices into the point cloud at which to sample grasp candidates.
std_msgs/Int64[] indices

================================================================================
MSG: gpd_ros/CloudSources
# This message holds a point cloud that can be a combination of point clouds 
# from different camera sources (at least one). For each point in the cloud, 
# this message also stores the index of the camera that produced the point.

# The point cloud.
sensor_msgs/PointCloud2 cloud

# For each point in the cloud, the index of the camera that acquired the point.
std_msgs/Int64[] camera_source

# A list of camera positions at which the point cloud was acquired.
geometry_msgs/Point[] view_points
================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field

================================================================================
MSG: std_msgs/Int64
int64 data
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['cloud_indexed']
  _slot_types = ['gpd_ros/CloudIndexed']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cloud_indexed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(detect_graspsRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cloud_indexed is None:
        self.cloud_indexed = gpd_ros.msg.CloudIndexed()
    else:
      self.cloud_indexed = gpd_ros.msg.CloudIndexed()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.cloud_indexed.cloud_sources.cloud.header.seq, _x.cloud_indexed.cloud_sources.cloud.header.stamp.secs, _x.cloud_indexed.cloud_sources.cloud.header.stamp.nsecs))
      _x = self.cloud_indexed.cloud_sources.cloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_indexed.cloud_sources.cloud.height, _x.cloud_indexed.cloud_sources.cloud.width))
      length = len(self.cloud_indexed.cloud_sources.cloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.cloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_indexed.cloud_sources.cloud.is_bigendian, _x.cloud_indexed.cloud_sources.cloud.point_step, _x.cloud_indexed.cloud_sources.cloud.row_step))
      _x = self.cloud_indexed.cloud_sources.cloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cloud_indexed.cloud_sources.cloud.is_dense
      buff.write(_get_struct_B().pack(_x))
      length = len(self.cloud_indexed.cloud_sources.camera_source)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.camera_source:
        _x = val1.data
        buff.write(_get_struct_q().pack(_x))
      length = len(self.cloud_indexed.cloud_sources.view_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.view_points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.cloud_indexed.indices)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.indices:
        _x = val1.data
        buff.write(_get_struct_q().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cloud_indexed is None:
        self.cloud_indexed = gpd_ros.msg.CloudIndexed()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.cloud_indexed.cloud_sources.cloud.header.seq, _x.cloud_indexed.cloud_sources.cloud.header.stamp.secs, _x.cloud_indexed.cloud_sources.cloud.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_indexed.cloud_sources.cloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_indexed.cloud_sources.cloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_indexed.cloud_sources.cloud.height, _x.cloud_indexed.cloud_sources.cloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.cloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_indexed.cloud_sources.cloud.is_bigendian, _x.cloud_indexed.cloud_sources.cloud.point_step, _x.cloud_indexed.cloud_sources.cloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.is_bigendian = bool(self.cloud_indexed.cloud_sources.cloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_indexed.cloud_sources.cloud.data = str[start:end]
      start = end
      end += 1
      (self.cloud_indexed.cloud_sources.cloud.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.is_dense = bool(self.cloud_indexed.cloud_sources.cloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.camera_source = []
      for i in range(0, length):
        val1 = std_msgs.msg.Int64()
        start = end
        end += 8
        (val1.data,) = _get_struct_q().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.camera_source.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.view_points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.view_points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.indices = []
      for i in range(0, length):
        val1 = std_msgs.msg.Int64()
        start = end
        end += 8
        (val1.data,) = _get_struct_q().unpack(str[start:end])
        self.cloud_indexed.indices.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.cloud_indexed.cloud_sources.cloud.header.seq, _x.cloud_indexed.cloud_sources.cloud.header.stamp.secs, _x.cloud_indexed.cloud_sources.cloud.header.stamp.nsecs))
      _x = self.cloud_indexed.cloud_sources.cloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_indexed.cloud_sources.cloud.height, _x.cloud_indexed.cloud_sources.cloud.width))
      length = len(self.cloud_indexed.cloud_sources.cloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.cloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_indexed.cloud_sources.cloud.is_bigendian, _x.cloud_indexed.cloud_sources.cloud.point_step, _x.cloud_indexed.cloud_sources.cloud.row_step))
      _x = self.cloud_indexed.cloud_sources.cloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cloud_indexed.cloud_sources.cloud.is_dense
      buff.write(_get_struct_B().pack(_x))
      length = len(self.cloud_indexed.cloud_sources.camera_source)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.camera_source:
        _x = val1.data
        buff.write(_get_struct_q().pack(_x))
      length = len(self.cloud_indexed.cloud_sources.view_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.cloud_sources.view_points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.cloud_indexed.indices)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_indexed.indices:
        _x = val1.data
        buff.write(_get_struct_q().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cloud_indexed is None:
        self.cloud_indexed = gpd_ros.msg.CloudIndexed()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.cloud_indexed.cloud_sources.cloud.header.seq, _x.cloud_indexed.cloud_sources.cloud.header.stamp.secs, _x.cloud_indexed.cloud_sources.cloud.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_indexed.cloud_sources.cloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_indexed.cloud_sources.cloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_indexed.cloud_sources.cloud.height, _x.cloud_indexed.cloud_sources.cloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.cloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_indexed.cloud_sources.cloud.is_bigendian, _x.cloud_indexed.cloud_sources.cloud.point_step, _x.cloud_indexed.cloud_sources.cloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.is_bigendian = bool(self.cloud_indexed.cloud_sources.cloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_indexed.cloud_sources.cloud.data = str[start:end]
      start = end
      end += 1
      (self.cloud_indexed.cloud_sources.cloud.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.cloud_indexed.cloud_sources.cloud.is_dense = bool(self.cloud_indexed.cloud_sources.cloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.camera_source = []
      for i in range(0, length):
        val1 = std_msgs.msg.Int64()
        start = end
        end += 8
        (val1.data,) = _get_struct_q().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.camera_source.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.cloud_sources.view_points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.cloud_indexed.cloud_sources.view_points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_indexed.indices = []
      for i in range(0, length):
        val1 = std_msgs.msg.Int64()
        start = end
        end += 8
        (val1.data,) = _get_struct_q().unpack(str[start:end])
        self.cloud_indexed.indices.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gpd_ros/detect_graspsResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import gpd_ros.msg
import std_msgs.msg

class detect_graspsResponse(genpy.Message):
  _md5sum = "cdff0a40c5f362fead62ab5c92e4e086"
  _type = "gpd_ros/detect_graspsResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """gpd_ros/GraspConfigList grasp_configs


================================================================================
MSG: gpd_ros/GraspConfigList
# This message stores a list of grasp configurations.

# The time of acquisition, and the coordinate frame ID.
Header header

# The list of grasp configurations.
gpd_ros/GraspConfig[] grasps

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: gpd_ros/GraspConfig
# This message describes a 2-finger grasp configuration by its 6-DOF pose,
# consisting of a 3-DOF position and 3-DOF orientation, and the opening
# width of the robot hand.

# Position
geometry_msgs/Point position # grasp position (bottom/base center of robot hand)

# Orientation represented as three axis (R = [approach binormal axis])
geometry_msgs/Vector3 approach # grasp approach direction
geometry_msgs/Vector3 binormal # hand closing direction
geometry_msgs/Vector3 axis # hand axis

std_msgs/Float32 width # Required aperture (opening width) of the robot hand

std_msgs/Float32 score # Score assigned to the grasp by the classifier

geometry_msgs/Point sample # point at which the grasp was found

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['grasp_configs']
  _slot_types = ['gpd_ros/GraspConfigList']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       grasp_configs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(detect_graspsResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.grasp_configs is None:
        self.grasp_configs = gpd_ros.msg.GraspConfigList()
    else:
      self.grasp_configs = gpd_ros.msg.GraspConfigList()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.grasp_configs.header.seq, _x.grasp_configs.header.stamp.secs, _x.grasp_configs.header.stamp.nsecs))
      _x = self.grasp_configs.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.grasp_configs.grasps)
      buff.write(_struct_I.pack(length))
      for val1 in self.grasp_configs.grasps:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.approach
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = val1.binormal
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v4 = val1.axis
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = val1.width
        _x = _v5.data
        buff.write(_get_struct_f().pack(_x))
        _v6 = val1.score
        _x = _v6.data
        buff.write(_get_struct_f().pack(_x))
        _v7 = val1.sample
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grasp_configs is None:
        self.grasp_configs = gpd_ros.msg.GraspConfigList()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.grasp_configs.header.seq, _x.grasp_configs.header.stamp.secs, _x.grasp_configs.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.grasp_configs.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.grasp_configs.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grasp_configs.grasps = []
      for i in range(0, length):
        val1 = gpd_ros.msg.GraspConfig()
        _v8 = val1.position
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v9 = val1.approach
        _x = _v9
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v10 = val1.binormal
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v11 = val1.axis
        _x = _v11
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v12 = val1.width
        start = end
        end += 4
        (_v12.data,) = _get_struct_f().unpack(str[start:end])
        _v13 = val1.score
        start = end
        end += 4
        (_v13.data,) = _get_struct_f().unpack(str[start:end])
        _v14 = val1.sample
        _x = _v14
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.grasp_configs.grasps.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.grasp_configs.header.seq, _x.grasp_configs.header.stamp.secs, _x.grasp_configs.header.stamp.nsecs))
      _x = self.grasp_configs.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.grasp_configs.grasps)
      buff.write(_struct_I.pack(length))
      for val1 in self.grasp_configs.grasps:
        _v15 = val1.position
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v16 = val1.approach
        _x = _v16
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v17 = val1.binormal
        _x = _v17
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v18 = val1.axis
        _x = _v18
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v19 = val1.width
        _x = _v19.data
        buff.write(_get_struct_f().pack(_x))
        _v20 = val1.score
        _x = _v20.data
        buff.write(_get_struct_f().pack(_x))
        _v21 = val1.sample
        _x = _v21
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grasp_configs is None:
        self.grasp_configs = gpd_ros.msg.GraspConfigList()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.grasp_configs.header.seq, _x.grasp_configs.header.stamp.secs, _x.grasp_configs.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.grasp_configs.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.grasp_configs.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grasp_configs.grasps = []
      for i in range(0, length):
        val1 = gpd_ros.msg.GraspConfig()
        _v22 = val1.position
        _x = _v22
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v23 = val1.approach
        _x = _v23
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v24 = val1.binormal
        _x = _v24
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v25 = val1.axis
        _x = _v25
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v26 = val1.width
        start = end
        end += 4
        (_v26.data,) = _get_struct_f().unpack(str[start:end])
        _v27 = val1.score
        start = end
        end += 4
        (_v27.data,) = _get_struct_f().unpack(str[start:end])
        _v28 = val1.sample
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.grasp_configs.grasps.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
class detect_grasps(object):
  _type          = 'gpd_ros/detect_grasps'
  _md5sum = '6544a7e3669d79f6069fe9d81fee1c1e'
  _request_class  = detect_graspsRequest
  _response_class = detect_graspsResponse
