// Generated by gencpp from file task_assembly/door_open_plannerRequest.msg
// DO NOT EDIT!


#ifndef TASK_ASSEMBLY_MESSAGE_DOOR_OPEN_PLANNERREQUEST_H
#define TASK_ASSEMBLY_MESSAGE_DOOR_OPEN_PLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>
#include <std_msgs/Bool.h>

namespace task_assembly
{
template <class ContainerAllocator>
struct door_open_plannerRequest_
{
  typedef door_open_plannerRequest_<ContainerAllocator> Type;

  door_open_plannerRequest_()
    : current_arm_joint_state()
    , interpolate_path()  {
    }
  door_open_plannerRequest_(const ContainerAllocator& _alloc)
    : current_arm_joint_state(_alloc)
    , interpolate_path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _current_arm_joint_state_type;
  _current_arm_joint_state_type current_arm_joint_state;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _interpolate_path_type;
  _interpolate_path_type interpolate_path;





  typedef boost::shared_ptr< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct door_open_plannerRequest_

typedef ::task_assembly::door_open_plannerRequest_<std::allocator<void> > door_open_plannerRequest;

typedef boost::shared_ptr< ::task_assembly::door_open_plannerRequest > door_open_plannerRequestPtr;
typedef boost::shared_ptr< ::task_assembly::door_open_plannerRequest const> door_open_plannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task_assembly::door_open_plannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task_assembly::door_open_plannerRequest_<ContainerAllocator1> & lhs, const ::task_assembly::door_open_plannerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_arm_joint_state == rhs.current_arm_joint_state &&
    lhs.interpolate_path == rhs.interpolate_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task_assembly::door_open_plannerRequest_<ContainerAllocator1> & lhs, const ::task_assembly::door_open_plannerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task_assembly

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6626cbb81764e0b2868ac23680ff5bb";
  }

  static const char* value(const ::task_assembly::door_open_plannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6626cbb81764e0bULL;
  static const uint64_t static_value2 = 0x2868ac23680ff5bbULL;
};

template<class ContainerAllocator>
struct DataType< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task_assembly/door_open_plannerRequest";
  }

  static const char* value(const ::task_assembly::door_open_plannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState current_arm_joint_state\n"
"std_msgs/Bool interpolate_path\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::task_assembly::door_open_plannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_arm_joint_state);
      stream.next(m.interpolate_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct door_open_plannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task_assembly::door_open_plannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task_assembly::door_open_plannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_arm_joint_state: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.current_arm_joint_state);
    s << indent << "interpolate_path: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.interpolate_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_ASSEMBLY_MESSAGE_DOOR_OPEN_PLANNERREQUEST_H
