// Generated by gencpp from file gpd_ros/CloudSamples.msg
// DO NOT EDIT!


#ifndef GPD_ROS_MESSAGE_CLOUDSAMPLES_H
#define GPD_ROS_MESSAGE_CLOUDSAMPLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gpd_ros/CloudSources.h>
#include <geometry_msgs/Point.h>

namespace gpd_ros
{
template <class ContainerAllocator>
struct CloudSamples_
{
  typedef CloudSamples_<ContainerAllocator> Type;

  CloudSamples_()
    : cloud_sources()
    , samples()  {
    }
  CloudSamples_(const ContainerAllocator& _alloc)
    : cloud_sources(_alloc)
    , samples(_alloc)  {
  (void)_alloc;
    }



   typedef  ::gpd_ros::CloudSources_<ContainerAllocator>  _cloud_sources_type;
  _cloud_sources_type cloud_sources;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _samples_type;
  _samples_type samples;





  typedef boost::shared_ptr< ::gpd_ros::CloudSamples_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpd_ros::CloudSamples_<ContainerAllocator> const> ConstPtr;

}; // struct CloudSamples_

typedef ::gpd_ros::CloudSamples_<std::allocator<void> > CloudSamples;

typedef boost::shared_ptr< ::gpd_ros::CloudSamples > CloudSamplesPtr;
typedef boost::shared_ptr< ::gpd_ros::CloudSamples const> CloudSamplesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpd_ros::CloudSamples_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpd_ros::CloudSamples_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpd_ros::CloudSamples_<ContainerAllocator1> & lhs, const ::gpd_ros::CloudSamples_<ContainerAllocator2> & rhs)
{
  return lhs.cloud_sources == rhs.cloud_sources &&
    lhs.samples == rhs.samples;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpd_ros::CloudSamples_<ContainerAllocator1> & lhs, const ::gpd_ros::CloudSamples_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpd_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gpd_ros::CloudSamples_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpd_ros::CloudSamples_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd_ros::CloudSamples_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd_ros::CloudSamples_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd_ros::CloudSamples_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd_ros::CloudSamples_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpd_ros::CloudSamples_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7acb8b5070bbe8bcd578eb420ebc4d9b";
  }

  static const char* value(const ::gpd_ros::CloudSamples_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7acb8b5070bbe8bcULL;
  static const uint64_t static_value2 = 0xd578eb420ebc4d9bULL;
};

template<class ContainerAllocator>
struct DataType< ::gpd_ros::CloudSamples_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpd_ros/CloudSamples";
  }

  static const char* value(const ::gpd_ros::CloudSamples_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpd_ros::CloudSamples_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message holds a point cloud and a list of samples at which the grasp \n"
"# detector should search for grasp candidates.\n"
"\n"
"# The point cloud.\n"
"gpd_ros/CloudSources cloud_sources\n"
"\n"
"# The samples, as (x,y,z) points, at which to search for grasp candidates. \n"
"geometry_msgs/Point[] samples\n"
"\n"
"================================================================================\n"
"MSG: gpd_ros/CloudSources\n"
"# This message holds a point cloud that can be a combination of point clouds \n"
"# from different camera sources (at least one). For each point in the cloud, \n"
"# this message also stores the index of the camera that produced the point.\n"
"\n"
"# The point cloud.\n"
"sensor_msgs/PointCloud2 cloud\n"
"\n"
"# For each point in the cloud, the index of the camera that acquired the point.\n"
"std_msgs/Int64[] camera_source\n"
"\n"
"# A list of camera positions at which the point cloud was acquired.\n"
"geometry_msgs/Point[] view_points\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64\n"
"int64 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gpd_ros::CloudSamples_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpd_ros::CloudSamples_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cloud_sources);
      stream.next(m.samples);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CloudSamples_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpd_ros::CloudSamples_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpd_ros::CloudSamples_<ContainerAllocator>& v)
  {
    s << indent << "cloud_sources: ";
    s << std::endl;
    Printer< ::gpd_ros::CloudSources_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_sources);
    s << indent << "samples[]" << std::endl;
    for (size_t i = 0; i < v.samples.size(); ++i)
    {
      s << indent << "  samples[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.samples[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPD_ROS_MESSAGE_CLOUDSAMPLES_H
